#!/bin/bash

echo "System is updating and upgrading, please wait for a while"
apt-get update -y
apt-get upgrade -y
echo "Java installation is under process"
apt-get install default-jre -y
apt-get install default-jdk -y
echo "Creating a directory to download required packages"
mkdir /opt/elk
echo "Please wait, Packages are downloading"
wget --directory-prefix=/opt/elk https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.4.2.deb
wget --directory-prefix=/opt/elk https://artifacts.elastic.co/downloads/kibana/kibana-6.4.2-amd64.deb
wget --directory-prefix=/opt/elk https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-6.4.2-amd64.deb
wget --directory-prefix=/opt/elk https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-6.4.2-amd64.deb
echo "Making downloaded packages executable"
chmod +x /opt/elk/*
echo "Installation in under process, please wait for a while"
dpkg -i /opt/elk/elasticsearch-6.4.2.deb
dpkg -i /opt/elk/kibana-6.4.2-amd64.deb
dpkg -i /opt/elk/metricbeat-6.4.2-amd64.deb
dpkg -i /opt/elk/filebeat-6.4.2-amd64.deb
sed -i 's/#network.host: 192.168.0.1/network.host: localhost/g' /etc/elasticsearch/elasticsearch.yml
sed -i 's/#http.port: 9200/http.port: 9200/g' /etc/elasticsearch/elasticsearch.yml
systemctl daemon-reload
systemctl enable elasticsearch.service
systemctl start elasticsearch.service
sed -i 's/#server.port: 5601/server.port: 5601/g' /etc/kibana/kibana.yml
sed -i 's/#server.host: "localhost"/server.host: "localhost"/g' /etc/kibana/kibana.yml
sed -i 's/#elasticsearch.url:/elasticsearch.url:/g' /etc/kibana/kibana.yml
systemctl daemon-reload
systemctl start kibana.service
systemctl enable kibana.service
wget -O /etc/metricbeat/metricbeat.yml https://raw.githubusercontent.com/aftab70/java/master/metricbeat_config
metricbeat modules enable system
wget -O /etc/metricbeat/modules.d/system.yml 
metricbeat -e
#echo "Installing nginx and the 'apache2-utils' packages to the system"
#apt install nginx apache2-utils -y
