#!/bin/bash


sudo -n true
if [ $? -ne 0 ]
    then
        echo "This script requires user to have passwordless sudo access"
        exit
fi

dependency_check_deb() {
java -version
if [ $? -ne 0 ]
    then
       
        sudo apt-get install defaults-jre -y && sudo apt-get install defaults-jre
        exit
fi
}
